export const musicList = [
  {
    id: "new-1",
    artist: "Kizz Daniel",
    duration: "2:56",
    title: "Cough (Odo)",
    cover: "/cover/cover_1.jpeg",
    audio: "/audio/audio_1.mp3",
  },
  {
    id: "new-2",
    artist: "Ayra Starr",
    duration: "3:09",
    title: "Rush",
    cover: "/cover/cover_2.jpeg",
    audio: "/audio/audio_2.mp3",
  },
  {
    id: "new-3",
    artist: "Bella Shmurda",
    duration: "2:09",
    title: "New Born Fela",
    cover: "/cover/cover_3.jpg",
    audio: "/audio/audio_3.mp3",
  },
  {
    id: "new-4",
    artist: "Blaqbonez ft JAE5",
    duration: "2:30",
    title: "Back In Uni",
    cover: "/cover/cover_4.jpeg",
    audio: "/audio/audio_4.mp3",
  },
  {
    id: "new-5",
    artist: "Pheelz ft Davido",
    duration: "2:14",
    title: "Electricity",
    cover: "/cover/cover_5.png",
    audio: "/audio/audio_5.mp3",
  },
  {
    id: "new-6",
    artist: "Oxlade",
    duration: "2:27",
    title: "KU LO SA",
    cover: "/cover/cover_6.webp",
    audio: "/audio/audio_6.mp3",
  },
  {
    id: "new-7",
    artist: "JAE5 ft Dave & BNXN",
    duration: "3:24",
    title: "Propeller",
    cover: "/cover/cover_7.png",
    audio: "/audio/audio_7.mp3",
  },
  {
    id: "new-8",
    artist: "Olamide",
    duration: "2:35",
    title: "We Outside",
    cover: "/cover/cover_8.jpeg",
    audio: "/audio/audio_8.mp3",
  },
  {
    id: "new-9",
    artist: "Joeboy",
    duration: "3:09",
    title: "Contour",
    cover: "/cover/cover_9.jpg",
    audio: "/audio/audio_9.mp3",
  },
  {
    id: "new-10",
    artist: "Zinoleesky",
    duration: "2:24",
    title: "Call Of Duty",
    cover: "/cover/cover_10.jpg",
    audio: "/audio/audio_10.mp3",
  },

  {
    id: "popular-1",
    artist: "Asake",
    duration: "2:19",
    title: "Terminator",
    cover: "/cover/cover_11.jpeg",
    audio: "/audio/audio_11.mp3",
  },
  {
    id: "popular-2",
    artist: "Magix ft Ayra Starr",
    duration: "2:26",
    title: "Love Don't Cost A Dime",
    cover: "/cover/cover_12.jpeg",
    audio: "/audio/audio_12.mp3",
  },
  {
    id: "popular-3",
    artist: "Burna Boy",
    duration: "2:52",
    title: "Last Last",
    cover: "/cover/cover_13.jpg",
    audio: "/audio/audio_13.mp3",
  },
  {
    id: "popular-4",
    artist: "Kizz Daniel ft Tekno",
    duration: "2:59",
    title: "Buga",
    cover: "/cover/cover_14.jpeg",
    audio: "/audio/audio_14.mp3",
  },
  {
    id: "popular-5",
    artist: "Steven ft Portable & TI Blaze",
    duration: "3:22",
    title: "Ali Remix",
    cover: "/cover/cover_15.png",
    audio: "/audio/audio_15.mp3",
  },
  {
    id: "popular-6",
    artist: "Asake ft Burna Boy",
    duration: "3:30",
    title: "Sungba Remix",
    cover: "/cover/cover_16.jpeg",
    audio: "/audio/audio_16.mp3",
  },
  {
    id: "popular-7",
    artist: "Fireboy",
    duration: "3:27",
    title: "Playboy",
    cover: "/cover/cover_17.jpeg",
    audio: "/audio/audio_17.mp3",
  },
  {
    id: "popular-8",
    artist: "BNXN ft Wande Coal",
    duration: "3:33",
    title: "Kenkele",
    cover: "/cover/cover_18.png",
    audio: "/audio/audio_18.mp3",
  },
  {
    id: "popular-9",
    artist: "Asake",
    duration: "2:33",
    title: "PBUY",
    cover: "/cover/cover_19.png",
    audio: "/audio/audio_19.mp3",
  },
  {
    id: "popular-10",
    artist: "Zinoleesky",
    duration: "2:05",
    title: "Loving You",
    cover: "/cover/cover_20.jpg",
    audio: "/audio/audio_20.mp3",
  },
];
